### ISSUE TITLE
Add sigmaFactor in getAllGenes.data.regulation.operon.arrangement.promoters

### ISSUE THREAD

**Issue by Pxcheco** [regulondbunam/GraphQL-api#114]
# TITLE
Add sigmaFactor in getAllGenes.data.regulation.operon.arrangement.promoters

## Description
El proyecto "Análisis exploratorio y visualización de datos de genes de RegulonDB." necesitamos contar el numero de factores sigmas que regulan al gene. Ya existe el subdocumento de promotores pero no tiene la propiedad del factor sigma que nos ayudaría a realizar el conteo. Por eso solicitimos agregar esta propiedad al subdocumento.

```
{
getAllGenes(limit:1000){
    data{
      gene{
        _id
        name
      }
    	regulation{
        operon{
          arrangement{
            promoters{
              _id
              name
              sigmaFactor # Aqui hay que agregar el nuevo campo
            }
          }
        }
      }
    }
}
}
```

## Expected behavior

Espero obtener el nombre del factor sigma para poder hacer el conteo.

Adicionalmente si es posible agregar numero de sigmas que regulan al genes en la sección de estadísticas.

**Comment by andresloal** [comment]
Hola, una primera versión de ésta solicitud ha sido generada en [RegulonDB-Prerelease](https://regulondb-prerelease.ccg.unam.mx/), en resumen:
 - El campo data.regulation.operon.arrangement.promoter.sigmaFactor es de tipo objeto y contiene dos propiedades de nombre _id y name que corresponden al sigma factor vinculado al promotor.
 - Por su parte la propiedad data.regulation.statistics.sigmaFactors es el numero total de sigma factors diferentes asociados a todos los promoters.
 
 Esta versión aun no estará disponible en RegulonDB online hasta el siguiente release, sin embargo formará parte de la versión 1.13.1 de este proyecto.

Te agradecería si lo pudieras revisar conectando tu proyecto a la url de prerelease (https://regulondb-prerelease.ccg.unam.mx/graphql) y probar con las tareas que lo utilizarán.
